### main  page
GET http://localhost:3000/

### get all posts
GET http://localhost:3000/api/posts/

### get single post
GET http://localhost:3000/api/posts/3 OR 1=1

### DELETE single post
DELETE  http://localhost:3000/api/posts/7

### POST CREATE POST
POST  http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "POST from rest",
  "author": "James Band",
  "date": "2000-12-24",
  "content": "Some important message....",
  "cat_id": 1
}


### get all categories
GET http://localhost:3000/api/categories