### main  page
GET http://localhost:3000/

### get all posts
GET http://localhost:3000/api/posts

### get single post
GET http://localhost:3000/api/posts/3 OR 1=1

### DELETE single post
DELETE  http://localhost:3000/api/posts/7
