### main  page
GET http://localhost:3000/

### get all posts
GET http://localhost:3000/api/posts/

### get single post
GET http://localhost:3000/api/posts/3 OR 1=1

### DELETE single post
DELETE  http://localhost:3000/api/posts/7

### POST CREATE POST
POST  http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "POST from category",
  "author": "James Band",
  "date": "2024-01-02",
  "content": "Some important message....",
  "cat_id": 3
}


### get all categories
GET http://localhost:3000/api/categories

### LOGIN User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "james@bond.com",
  "password": "123456"
}

### REGISTER User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "james@band.com",
  "password": "123456"
}